### ISSUE TITLE
Recuperar la historia de los artículos

### ISSUE THREAD

**Issue by fauno** [edsl/articulos#1]
y las ramas también!

**Comment by mauriciopasquier** [comment]
Ni miraste el repo... la historia está. Por las ramas, paciencia jóven padawan.

**Comment by fauno** [comment]
ah no vi que estaba paginada, vi solo hasta diciembre 2012 (!)

**Comment by fauno** [comment]
hacé una guía

**Comment by fauno** [comment]
mcfly!!
