### ISSUE TITLE
jopp

### ISSUE THREAD

**Issue by mauriciopasquier** [edsl/articulos#4]
Estos estaban para arrancar la traducción pero no los migré
- jopp_hacklabs-and-hackerspaces
- jopp_ten-patterns-developed-by-the-oekonux-project

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> Estos estaban para arrancar la traducción pero no los migré
> - jopp_hacklabs-and-hackerspaces
> - jopp_ten-patterns-developed-by-the-oekonux-project

migralos eventualmente los traduciremos

## 

 D

**Comment by mauriciopasquier** [comment]
pusheá una rama por cada uno.. no voy a migrar 1 commit de texto original

**Comment by fauno** [comment]
el de hacklabs ya lo publicamos, el otro ya no da me parece
