### ISSUE TITLE
justicia

### ISSUE THREAD

**Issue by mauriciopasquier** [edsl/articulos#9]
pasamos todos los

> Traducido por A. Corregido por B

a

> Traducido por A y B

?

**Comment by fauno** [comment]
depende, hay algunos correctores que solo mandaron cosas gramaticales...

**Comment by mauriciopasquier** [comment]
On Tue, Aug 19, 2014 at 07:05:40AM -0700, fauno wrote:

> depende, hay algunos correctores que solo mandaron cosas gramaticales...

igual los pondría. Pero es discutible.. lo que no es discutible es que hay un
laburo de retraducción zarpado en algunos (atoms por ejemplo), y creo que tes
también corrigió un montón de cosas. O sea, mi criterio sería:
- traductores si contrastaste con el original
- correctores si sólo leíste el texto traducido

podríamos ponerlo en el CONTRIBUTING ("agregate a..")

##

**Comment by fauno** [comment]
Mauricio Pasquier Juan notifications@github.com writes:

> On Tue, Aug 19, 2014 at 07:05:40AM -0700, fauno wrote:
> 
> > depende, hay algunos correctores que solo mandaron cosas gramaticales...
> 
> igual los pondría. Pero es discutible.. lo que no es discutible es que hay un
> laburo de retraducción zarpado en algunos (atoms por ejemplo), y creo que tes
> también corrigió un montón de cosas. O sea, mi criterio sería:
> - traductores si contrastaste con el original
> - correctores si sólo leíste el texto traducido
> 
> podríamos ponerlo en el CONTRIBUTING ("agregate a..")

me parece bien

## 

:D
